### ISSUE TITLE
Fsm-crud - error on start

### ISSUE THREAD

**Issue by tbergman** [coodoo/xstate-examples#3]
fsm-crud example (Chrome 76.0.3809.132 / MacOS high sierra) :
1. yarn start
2. getting error: "TypeError: eventObject.type.indexOf is not a function"

**Comment by coodoo** [comment]
All examples had been rewritten, let me know if there's still issues.

**Comment by tbergman** [comment]
Thanks Jeremy, works great. Thanks a lot for creating these excellent examples!
